In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#Milestone 2: Data Exploration & Initial Preprocessing

In [6]:
!ls

flights.csv  sample_data


In [7]:
# !unzip flights.csv.zip

In [8]:
df = pd.read_csv('flights.csv')

In [9]:
# from google.colab import drive
# drive.mount('/content/drive')

In [10]:
df.head()

id  year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0   0  2013      1    1     517.0             515        2.0     830.0   
1   1  2013      1    1     533.0             529        4.0     850.0   
2   2  2013      1    1     542.0             540        2.0     923.0   
3   3  2013      1    1     544.0             545       -1.0    1004.0   
4   4  2013      1    1     554.0             600       -6.0     812.0   

   sched_arr_time  arr_delay  ... flight  tailnum origin dest air_time  \
0             819       11.0  ...   1545   N14228    EWR  IAH    227.0   
1             830       20.0  ...   1714   N24211    LGA  IAH    227.0   
2             850       33.0  ...   1141   N619AA    JFK  MIA    160.0   
3            1022      -18.0  ...    725   N804JB    JFK  BQN    183.0   
4             837      -25.0  ...    461   N668DN    LGA  ATL    116.0   

   distance  hour  minute            time_hour                    name  
0      1400     5      15  2013-01-01 05:00:00   United Air Lines Inc.  
1      1416     5      29  2013-01-01 05:00:00   United Air Lines Inc.  
2      1089     5      40  2013-01-01 05:00:00  American Airlines Inc.  
3      1576     5      45  2013-01-01 05:00:00         JetBlue Airways  
4       762     6       0  2013-01-01 06:00:00    Delta Air Lines Inc.  

[5 rows x 21 columns]

In [11]:
df.columns

Index(['id', 'year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour', 'name'],
      dtype='object')

**Column Descriptions:**

id: A unique identifier for each flight record in the dataset.

month: The month in which the flight took place (1 to 12).

day: The day of the month on which the flight took place (1 to 31).

dep_time: The actual local departure time of the flight, in 24-hour format (hhmm).

sched_dep_time: The scheduled local departure time of the flight, in 24-hour format (hhmm).

dep_delay: The difference between the actual and scheduled departure times of the flight, in minutes. A positive value indicates a delayed departure, while a negative value indicates an early departure.

arr_time: The actual local arrival time of the flight, in 24-hour format (hhmm).

sched_arr_time: The scheduled local arrival time of the flight, in 24-hour format (hhmm).

arr_delay: The difference between the actual and scheduled arrival times of the flight, in minutes. A positive value indicates a delayed arrival, while a negative value indicates an early arrival.

carrier: The two-letter code of the airline carrier for the flight.

flight: The flight number of the flight.

tailnum: The unique identifier of the aircraft used for the flight.

origin: The three-letter code of the airport of origin for the flight.

dest: The three-letter code of the destination airport for the flight.

air_time: The duration of the flight, in minutes.

distance: The distance between the origin and destination airports, in miles.



In [12]:
df['year'].unique()

array([2013])

In [13]:
df=df.drop(columns=['year', 'name', 'hour', 'minute', 'time_hour'])

In [14]:
df.isna().sum()

id                   0
month                0
day                  0
dep_time          8255
sched_dep_time       0
dep_delay         8255
arr_time          8713
sched_arr_time       0
arr_delay         9430
carrier              0
flight               0
tailnum           2512
origin               0
dest                 0
air_time          9430
distance             0
dtype: int64

In [15]:
df = df.dropna(subset=['dep_time', 'arr_time', 'arr_delay', 'air_time'])

In [16]:
df.isna().sum()

id                0
month             0
day               0
dep_time          0
sched_dep_time    0
dep_delay         0
arr_time          0
sched_arr_time    0
arr_delay         0
carrier           0
flight            0
tailnum           0
origin            0
dest              0
air_time          0
distance          0
dtype: int64

In [17]:
df.dtypes

id                  int64
month               int64
day                 int64
dep_time          float64
sched_dep_time      int64
dep_delay         float64
arr_time          float64
sched_arr_time      int64
arr_delay         float64
carrier            object
flight              int64
tailnum            object
origin             object
dest               object
air_time          float64
distance            int64
dtype: object

In [18]:
df['dep_time'] = df['dep_time'].astype(int)
df['dep_delay'] = df['dep_delay'].astype(int)
df['arr_time'] = df['arr_time'].astype(int)
df['dep_time'] = df['dep_time'].astype(int)
df['arr_delay'] = df['arr_delay'].astype(int)
df['air_time'] = df['air_time'].astype(int)

<ipython-input-18-a06ace3481ab>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dep_time'] = df['dep_time'].astype(int)
<ipython-input-18-a06ace3481ab>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['dep_delay'] = df['dep_delay'].astype(int)
<ipython-input-18-a06ace3481ab>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/

In [19]:
df.dtypes

id                 int64
month              int64
day                int64
dep_time           int64
sched_dep_time     int64
dep_delay          int64
arr_time           int64
sched_arr_time     int64
arr_delay          int64
carrier           object
flight             int64
tailnum           object
origin            object
dest              object
air_time           int64
distance           int64
dtype: object

In [20]:
df.shape

(327346, 16)

In [21]:
df.columns

Index(['id', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance'],
      dtype='object')

In [22]:
df['month'].unique()

array([ 1, 10, 11, 12,  2,  3,  4,  5,  6,  7,  8,  9])

In [23]:
df['day'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [24]:
len(df['dep_time'].unique())

1317

In [25]:
len(df['sched_dep_time'].unique())

1020

In [26]:
df['dep_delay'].describe()

count    327346.000000
mean         12.555156
std          40.065688
min         -43.000000
25%          -5.000000
50%          -2.000000
75%          11.000000
max        1301.000000
Name: dep_delay, dtype: float64

In [27]:
len(df['arr_time'].unique())

1410

In [28]:
len(df['sched_arr_time'].unique())

1162

In [29]:
df['arr_delay'].describe()

count    327346.000000
mean          6.895377
std          44.633292
min         -86.000000
25%         -17.000000
50%          -5.000000
75%          14.000000
max        1272.000000
Name: arr_delay, dtype: float64

In [30]:
df['carrier'].unique()

array(['UA', 'AA', 'B6', 'DL', 'EV', 'MQ', 'US', 'WN', 'VX', 'FL', 'AS',
       '9E', 'F9', 'HA', 'YV', 'OO'], dtype=object)

In [31]:
len(df['flight'].unique())

3835

In [32]:
len(df['tailnum'].unique())

4037

In [33]:
df['origin'].unique()

array(['EWR', 'LGA', 'JFK'], dtype=object)

In [34]:
df['dest'].unique()

array(['IAH', 'MIA', 'BQN', 'ATL', 'ORD', 'FLL', 'IAD', 'MCO', 'PBI',
       'TPA', 'LAX', 'SFO', 'DFW', 'BOS', 'LAS', 'MSP', 'DTW', 'RSW',
       'SJU', 'PHX', 'BWI', 'CLT', 'BUF', 'DEN', 'SNA', 'MSY', 'SLC',
       'XNA', 'MKE', 'SEA', 'ROC', 'SYR', 'SRQ', 'RDU', 'CMH', 'JAX',
       'CHS', 'MEM', 'PIT', 'SAN', 'DCA', 'CLE', 'STL', 'MYR', 'JAC',
       'MDW', 'HNL', 'BNA', 'AUS', 'BTV', 'PHL', 'STT', 'EGE', 'AVL',
       'PWM', 'IND', 'SAV', 'CAK', 'HOU', 'LGB', 'DAY', 'ALB', 'BDL',
       'MHT', 'MSN', 'GSO', 'CVG', 'BUR', 'RIC', 'GSP', 'GRR', 'MCI',
       'ORF', 'SAT', 'SDF', 'PDX', 'SJC', 'OMA', 'CRW', 'OAK', 'SMF',
       'TYS', 'PVD', 'DSM', 'PSE', 'TUL', 'BHM', 'OKC', 'CAE', 'HDN',
       'BZN', 'MTJ', 'EYW', 'PSP', 'ACK', 'BGR', 'ABQ', 'ILM', 'MVY',
       'SBN', 'LEX', 'CHO', 'TVC', 'ANC'], dtype=object)

In [35]:
df['air_time'].describe()

count    327346.000000
mean        150.686460
std          93.688305
min          20.000000
25%          82.000000
50%         129.000000
75%         192.000000
max         695.000000
Name: air_time, dtype: float64

In [36]:
df['distance'].describe()

count    327346.000000
mean       1048.371314
std         735.908523
min          80.000000
25%         509.000000
50%         888.000000
75%        1389.000000
max        4983.000000
Name: distance, dtype: float64

In [37]:
# NOTE: Pairplots from Milestone 2 currently commented out since they take a long time to run.

# sns.pairplot(df, hue='carrier')
# plt.show()

In [38]:
# sns.pairplot(df, hue='origin')
# plt.show()

In [39]:
# sns.pairplot(df, hue='dest')
# plt.show()

#Milestone 3: Intial Model

In [40]:
# function to convert hhmm time format to number of minutes since January 1st 2013 (written by Devam)

def convert_to_mins(month, day, time):

    if month > 1:
      day += 31
    if month > 2:
      day += 28
    if month > 3:
      day += 31
    if month > 4:
      day += 30
    if month > 5:
      day += 31
    if month > 6:
      day += 30
    if month > 7:
      day += 31
    if month > 8:
      day += 31
    if month > 9:
      day += 30
    if month > 10:
      day += 31
    if month > 11:
      day += 30

    minutes_in_day = (day - 1) * 24 * 60

    hours = time // 100
    minutes = time % 100

    total_minutes = (hours * 60) + minutes

    total_minutes_passed = minutes_in_day + total_minutes

    return total_minutes_passed

In [41]:
# function that calculates time difference ("offset") between origin and destination airport, taking daylight savings into consideration (written by Sydney)
# dest is string; month, day, dep_time are ints; returns int representing how many hours destination airport's time zone is ahead of origin airport's time zone
def offset(dest, month, day, dep_time):

  timezone_dict = {'ABQ':'MDT', 'ACK':'EDT', 'ALB':'EDT', 'ANC':'ADT', 'ATL':'EDT', 'AUS':'CDT', 'AVL':'EDT', 'BDL':'EDT', 'BGR':'EDT', 'BHM':'CDT', 'BNA':'CDT', 'BOS':'EDT',
 'BQN':'ADT', 'BTV':'EDT', 'BUF':'EDT', 'BUR':'PDT', 'BWI':'EDT', 'BZN':'MDT', 'CAE':'EDT', 'CAK':'EDT', 'CHO':'EDT', 'CHS':'EDT', 'CLE':'EDT', 'CLT':'EDT',
 'CMH':'EDT', 'CRW':'EDT', 'CVG':'EDT', 'DAY':'EDT', 'DCA':'EDT', 'DEN':'MDT', 'DFW':'CDT', 'DSM':'CDT', 'DTW':'EDT', 'EGE':'MDT', 'EYW':'EDT', 'FLL':'EDT',
 'GRR':'EDT', 'GSO':'EDT', 'GSP':'EDT', 'HDN':'MDT', 'HNL':'HST', 'HOU':'CDT', 'IAD':'EDT', 'IAH':'CDT', 'ILM':'EDT', 'IND':'EDT', 'JAC':'MDT', 'JAX':'EDT',
 'LAS':'PDT', 'LAX':'PDT', 'LEX':'EDT', 'LGB':'PDT', 'MCI':'CDT', 'MCO':'EDT', 'MDW':'CDT', 'MEM':'CDT', 'MHT':'EDT', 'MIA':'EDT', 'MKE':'CDT', 'MSN':'CDT',
 'MSP':'CDT', 'MSY':'CDT', 'MTJ':'MDT', 'MVY':'EDT', 'MYR':'EDT', 'OAK':'PDT', 'OKC':'CDT', 'OMA':'CDT', 'ORD':'CDT', 'ORF':'EDT', 'PBI':'EDT', 'PDX':'PDT',
 'PHL':'EDT', 'PHX':'MST', 'PIT':'EDT', 'PSE':'AST', 'PSP':'PDT', 'PVD':'EDT', 'PWM':'EDT', 'RDU':'EDT', 'RIC':'EDT', 'ROC':'EDT', 'RSW':'EDT', 'SAN':'PDT',
 'SAT':'CDT', 'SAV':'EDT', 'SBN':'EDT', 'SDF':'EDT', 'SEA':'PDT', 'SFO':'PDT', 'SJC':'PDT', 'SJU':'AST', 'SLC':'MDT', 'SMF':'PDT', 'SNA':'PDT', 'SRQ':'EDT',
 'STL':'CDT', 'STT':'AST', 'SYR':'EDT', 'TPA':'EDT', 'TUL':'CDT', 'TVC':'PDT', 'TYS':'PDT', 'XNA':'CDT'}

  offset_dict = {'AST':0, 'MDT':-2, 'ADT':1, 'PDT':-3, 'EDT':0, 'MST':-3, 'CDT':-1, 'HST':-6}

  # will not consider flights that take off and land while daylight savings turned on/off since it has negligible effect
  # just considering whether daylight savings enforced when plane taking off, then assuming daylight savings also enforced when it landed
  if (month >= 3 and day >= 10 and dep_time >= 200) and (month <= 11 and day <=3 and dep_time <= 200):
    offset_dict[timezone_dict[dest]] # during daylight savings, so use offset_dict value offset directly
  else:
    if (timezone_dict[dest][1] == 'S'): # not during daylight savings, and doesn't observe daylight savings
      return offset_dict[timezone_dict[dest]] + 1
    else: # not during daylight savings, but does observe daylight savings
      return offset_dict[timezone_dict[dest]]

In [42]:
# oe-hot encoding of carriers, origin airports, and destination airports (written by Aahil)

carriers = df['carrier'].unique().tolist()
origins = df['origin'].unique().tolist()
dests = df['dest'].unique().tolist()
def get_carrier(carriername):
    # return np.array(pd.get_dummies(df[['carrier']])['carrier_'+carriername].astype(int)).tolist()
    output = [0]*len(carriers)
    output[carriers.index(carriername)] = 1
    return output

def get_origin(originname):
    # return np.array(pd.get_dummies(df[['origin']])['origin_'+originname].astype(int)).tolist()
    output = [0]*len(origins)
    output[origins.index(originname)] = 1
    return output

def get_dest(destname):
    # return np.array(pd.get_dummies(df[['dest']])['dest_'+destname].astype(int)).tolist()
    output = [0]*len(dests)
    output[dests.index(destname)] = 1
    return output


In [43]:
get_carrier('AA')

[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [44]:
df.head()

id  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0   0      1    1       517             515          2       830   
1   1      1    1       533             529          4       850   
2   2      1    1       542             540          2       923   
3   3      1    1       544             545         -1      1004   
4   4      1    1       554             600         -6       812   

   sched_arr_time  arr_delay carrier  flight tailnum origin dest  air_time  \
0             819         11      UA    1545  N14228    EWR  IAH       227   
1             830         20      UA    1714  N24211    LGA  IAH       227   
2             850         33      AA    1141  N619AA    JFK  MIA       160   
3            1022        -18      B6     725  N804JB    JFK  BQN       183   
4             837        -25      DL     461  N668DN    LGA  ATL       116   

   distance  
0      1400  
1      1416  
2      1089  
3      1576  
4       762

In [45]:
 df.iloc[0]['day']

1

In [46]:
# function that returns whether a flight takes off and lands on different dates (written by Sydney)

def get_different_day(dest, month, day, dep_time, arr_time):
  new_arr_time = offset(dest, month, day, dep_time) + arr_time
  if new_arr_time < 0:
    new_arr_time += 2400
  if new_arr_time < dep_time:
    return True
  else:
    return False

In [47]:
def feature(index):
  row = df.iloc[index]
  output = [1]
  output += [row['distance']/5000]
  output += [convert_to_mins(row['month'], row['day'], row['sched_dep_time'])/550000]
  arrtime = convert_to_mins(row['month'], row['day'], row['arr_time'])
  if get_different_day(row['dest'], row['month'], row['day'], row['sched_dep_time'], row['sched_arr_time']):
    arrtime += 60*24
  output += [arrtime/550000]
  output += [convert_to_mins(1, 1, row['dep_delay'])/144]
  output += get_carrier(row['carrier'])
  output += get_origin(row['origin'])
  output += get_dest(row['dest'])
  output += [offset(row.dest, row.month, row.day, row.dep_time)]
  return np.array(output)


In [48]:
len(feature(0))

129

In [49]:
dataset = np.array([feature(i).reshape(1,129) for i in range(df.shape[0])])

In [50]:
len(dataset)

327346

In [51]:
len(dataset[0])

1

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, y_train, y_test = train_test_split(dataset, df.arr_delay, test_size=0.2, random_state=42)

In [54]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, BatchNormalization
from sklearn.metrics import mean_squared_error

In [55]:
# Recurrent Neural Network model (written by Genie)

model = Sequential()

# IF you are running with a GPU, try out the CuDNNLSTM layer type instead (don't pass an activation, tanh is required)
model.add(LSTM(128, input_shape=[1,129], activation='relu', return_sequences=True))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(LSTM(128, activation='relu'))
model.add(Dropout(0.1))
model.add(BatchNormalization())

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(10, activation='softmax'))

opt = tf.keras.optimizers.Adam(learning_rate=0.001) #decay=1e-6

# Compile model
model.compile(
    loss='mse',
    optimizer=opt,
    metrics=['mse'],
)

In [56]:
X_train = X_train.reshape(-1, 1, 129)
X_test  = X_test.reshape(-1, 1, 129)
# y_train = y_train.reshape(-1, 1, 1)
# y_test = y_test.reshape(-1, 1, 1)

In [57]:
X_train[:2], y_train[:2], X_test[:2], y_test[:2]

(array([[[ 1.        ,  0.1438    ,  0.05388909,  0.05404727,
           0.22916667,  1.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  1.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           1.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        ,  0.        ,  0.        ,
        

In [58]:
model.fit(X_train,
          y_train,
          epochs=3,
          validation_data=(X_test, y_test))

Epoch 1/3
8184/8184 [==============================] - 97s 11ms/step - loss: 2044.3048 - mse: 2044.3048 - val_loss: 2014.2782 - val_mse: 2014.2782
Epoch 2/3
8184/8184 [==============================] - 91s 11ms/step - loss: 2044.3035 - mse: 2044.3035 - val_loss: 2014.2782 - val_mse: 2014.2782
Epoch 3/3
8184/8184 [==============================] - 91s 11ms/step - loss: 2044.3026 - mse: 2044.3026 - val_loss: 2014.2782 - val_mse: 2014.2782


In [59]:
np.mean(y_train)

6.8759641967954295

In [60]:
mean_squared_error(y_test, [np.mean(y_train)]*len(y_test))

1967.0509417086892